// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj5Yn0IXYzwWB8NAjSG3qbP9v7CwlgglY',
    authDomain: 'ecommerce-app-98556.firebaseapp.com',
    projectId: 'ecommerce-app-98556',
    storageBucket: 'ecommerce-app-98556.firebasestorage.app',
    messagingSenderId: '311036486282',
    appId: '1:311036486282:web:71f1d109d1aa4a4eaf0373',
    measurementId: 'G-Q7W0N3W69N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1wjLrplEik2oUOnHd4WXkd6RmRqBGPCA',
    appId: '1:311036486282:android:68eafbc1429d4697af0373',
    messagingSenderId: '311036486282',
    projectId: 'ecommerce-app-98556',
    storageBucket: 'ecommerce-app-98556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX96AtHgzRC3ikT_3a6w12LiVR79FoOQU',
    appId: '1:311036486282:ios:919458ac6eb1f1d5af0373',
    messagingSenderId: '311036486282',
    projectId: 'ecommerce-app-98556',
    storageBucket: 'ecommerce-app-98556.firebasestorage.app',
    iosClientId:
        '311036486282-kfv429qv9hcj3vdivshaba55sphue5ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX96AtHgzRC3ikT_3a6w12LiVR79FoOQU',
    appId: '1:311036486282:ios:919458ac6eb1f1d5af0373',
    messagingSenderId: '311036486282',
    projectId: 'ecommerce-app-98556',
    storageBucket: 'ecommerce-app-98556.firebasestorage.app',
    iosClientId:
        '311036486282-kfv429qv9hcj3vdivshaba55sphue5ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
